### ISSUE TITLE
sqlitecloud.types.SQLiteCloudException: An error occurred while initializing the socket.

### ISSUE THREAD

**Issue by maejikal** [sqlitecloud/sqlitecloud-py#15]
I have trouble connecting to the database with the sqlitecloud module. My code is exactly the same as the example code, with the exception of the connection string which I had changed according to my own API key. Please advise. 

<img width="1022" alt="Screenshot 2024-06-13 at 12 45 58" src="https://github.com/sqlitecloud/sqlitecloud-py/assets/69302838/e8f81302-3829-4f63-a332-9b264cea9c67">

**Comment by danielebriggi** [comment]
Thank you maejikal, it looks like the missing certificates for Python might be causing the problem. To resolve try this:

- Run the `Install Certificates.command` script in your Python installation directory.

It seems to be a common issue as reported here: https://stackoverflow.com/a/58525755

If you encounter any further issues or have any questions, please let me know.

**Comment by maejikal** [comment]
Thank you! This fixed it.

<img width="779" alt="Screenshot 2024-06-14 at 08 28 19" src="https://github.com/sqlitecloud/sqlitecloud-py/assets/69302838/73aa2083-267b-4b3a-b844-b34d54e5c580">
