### ISSUE TITLE
python / driver not returning appropriate lastrowid

### ISSUE THREAD

**Issue by jacobprall** [sqlitecloud/sqlitecloud-py#29]
### Observations from the Log 
1. The log shows that new locations are being inserted, but their `id` values are coming back as `None`: ``` Inserted new location: 'Desk Bottom Drawer' with id: None ``` 
2. This is a critical issue because the `id` should be automatically generated when inserting a new location, and the `lastrowid` should return the correct `id`. 
3. The `None` value for `id` is causing cascading issues when trying to insert items, leading to further errors. 
### Possible Causes and Solutions 
This issue could be caused by a few things: 
1. **Using a `connection` object that does not properly track the `lastrowid`.** Depending on how your connection is set up (especially if using certain wrappers or drivers), it may not support retrieving the `lastrowid` correctly. 
2. **Improper transaction handling or connection settings** could also result in the `lastrowid` being lost. 
### Next Steps 
1. **Investigate the `connect` Function**: - I will now review the current script to analyze how the connection is established and how the transaction is handled. Let me take a look at the script you uploaded. 
### Analysis of the Current Script The key part of the script is the following section: ```python cursor.execute("INSERT INTO locations (name) VALUES (?)", (location,)) location_id = cursor.lastrowid [logger.info](http://logger.info/)(f"Inserted new location: '{location}' with id: {location_id}") ``` The issue is that `cursor.lastrowid` is returning `None`. This can happen for a few reasons: 1. **The Connection to the SQLite Database**: - The script uses `sqlitecloud.connect(CONNECTION_STRING)`, which might not handle `lastrowid` as expected depending on the underlying implementation. The `sqlitecloud` library might be a wrapper that does not fully support returning `lastrowid` properly. 
2. **Transaction Handling**: - If the transaction is not fully committed or the database is in an unexpected state, `lastrowid` could be lost. 
### Potential Solutions: 
1. **Explicitly Commit the Transaction Immediately After Inserting a Location**: - Ensure that the location is fully committed before retrieving `lastrowid`: ```python cursor.execute("INSERT INTO locations (name) VALUES (?)", (location,)) cursor.connection.commit() # Force commit location_id = cursor.lastrowid [logger.info](http://logger.info/)(f"Inserted new location: '{location}' with id: {location_id}") ``` 
2. **Switch to a Standard SQLite Connection for Testing**: - If possible, try using the built-in `sqlite3` module without the `sqlitecloud` wrapper to see if it behaves as expected. This will help you determine if the issue is specific to the `sqlitecloud` connection. 
3. **Debugging the Connection Object**: - Add some debug information about the connection and cursor objects to see if there’s anything unusual: ```python logger.debug(f"Cursor details: {cursor}") logger.debug(f"Connection details: {cursor.connection}") ``` 
4. **Consider Using a Different Library or Approach**: - If the issue persists and you find that the `sqlitecloud` library does not behave consistently, it might be worth considering another solution or a different library that better supports your use case. Let me know if you’d like to explore any of these solutions further! If you decide to stick with this implementation, we can dig deeper into the connection handling to ensure it works as expected.

**Comment by danielebriggi** [comment]
the last version (ready to go live, `v0.80`) of python sdk implements `lastrowid`
